const d = {
  username: data.data.account.name,
  level: data.data.battlePass.level,
  wins: stats.wins,
  kd: stats.kd,
  kills: stats.kills,
  matches: stats.matches,
  winRate: stats.winRate,
  timePlayed: stats.minutesPlayed,
  timeWindow: prettyTimeWindow,
  playersOutlived: stats.playersOutlived,
  top3: stats.top3,
  top5: stats.top5,
  top6: stats.top6,
  top10: stats.top10,
  top12: stats.top12,
  top25: stats.top25,
};
